version: '3'
services:

 full:
  image: blckchnd/peerplays-mainnet:1.0.0
  build:
    context: ./dkr
  environment:
   - 'PEERPLAYSD_SEED_NODES=seed.ppy.blckchnd.com:6112'
   - 'PEERPLAYSD_RPC_ENDPOINT=0.0.0.0:8090'
   - 'PEERPLAYSD_P2P_ENDPOINT=0.0.0.0:6666'
   - 'PEERPLAYSD_PRIVATE_KEY=["PPY6rvDcF9SzWHc8KwZPETpSV3WaMf7Mw87NiSFqrg5NiXg6VHtSR","5J1p6r6tP2KVMFFVjUFySVo9StMYf3cyREbgVcbbQ3MJho9zHjs"]'
   - 'PEERPLAYSD_WITNESS_ID="1.6.68"'
   - 'PEERPLAYSD_REQUIRED_PARTICIPATION=true'
   - 'PEERPLAYSD_REPLAY=Yes'   # Replays if the variable exists
  ports:
   - "94.130.250.17:6666:6666"
   - "94.130.250.17:8090:8090"
  volumes:
   - "/data/store/peerplays/full:/var/lib/peerplays"
